# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  

development:
  <<: *default
  database: railsgirl_idea_developments